### ISSUE TITLE
Установка

### ISSUE THREAD

**Issue by Allkorolev** [hostcc/energomera-hass-mqtt#7]
Добрый  день, подскажите как можно установить помимо docker? 
У меня Home Assistant установлен как OS и соответственно Ваш пакет поставить не могу.

**Comment by hostcc** [comment]
@Allkorolev , `energomera-hass-mqtt` использует MQTT для передачи показаний счетчика в Home Assistant.

Основной сценарий:
* Вспомогательное устройство (я использую Raspberry PI Zero) и [USB IEC считыватель](https://www.aliexpress.com/snapshot/0.html?spm=a2g39.orderdetails.order_info.4.34c64aa6NR6TsZ&orderId=8143003118925962&productId=1731230485&_ga=2.49102886.1060743940.1660555316-264710938.1660555316), подключенный к нему
* MQTT broker (использую Eclipse Mosquitto) - на другом устройстве
* MQTT integration для Home Assistant - на другом устройстве

Отличается ли этот сценарий от Вашего?

Если Вы хотите сделать весь сценарий на одном устройстве с HASS OS, то MQTT broker и `energomera-hass-mqtt` придется устанавливать каким-либо методом. Однако, я такой вариант не проверял практически и могу предположить, что
* Для MQTT broker можно попробовать `Mosquitto broker` add-on
* Для установки `energomera-hass-mqtt` можно попробовать или дополнительный Docker container для HASS OS (думаю, что это unsupported scenario), либо сделать для него add-on, либо еще какие-то варианты
